### ISSUE TITLE
Startup jobs (cron/backup) don't work

### ISSUE THREAD

**Issue by mickenorlen** [selim13/docker-automysqlbackup#1]
I have a problem, might be something simple. 

I'm using docker-compose like below (i'm not writing all the input/output since i have multiple files/containers etc). The mysqlbackup container works fine, i can use:  
 `docker exec -it mysqlbackup sh` and run automysqlbackup manually - but the cron jobs or even starting `docker-compose up -d" without CRON_SCHEDULE specified doesn't do anything for me. Thanks for any input.

```
  mysqlbackup:
    container_name: mysqlbackup
    image: selim13/automysqlbackup
    volumes:
      - "mysqlbackup-data:/backup"
    environment:
      - USERNAME=user
      - PASSWORD=password
      - DBHOST=typo3_db
      - CRON_SCHEDULE="0 * * * *"
    depends_on:
      - typo3_db
```

docker ps 
```
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                           NAMES
3200d1e77a3d        selim13/automysqlbackup                "start.sh"               6 minutes ago       Up 6 minutes                                        mysqlbackup
```

docker logs mysqlbackup gives:
```
2017/10/06 22:24:07 Running version:
2017/10/06 22:24:07 new cron: 0 "0 * * * *"
2017/10/06 22:24:07 Opening port 18080 for health checking
```

**Comment by nepda** [comment]
I've the same problem. Executing without `CRON_SCHEDULE` works fine:

    docker-compose run -e CRON_SCHEDULE='' mysqlbackup

Any suggestions how to get things work or how to debug the problem?

**Comment by selim13** [comment]
Wow, I'm very sorry for the long reply. Looks like I was unsubscribed from the notifications for my own repo... Anyway:

@mickenorlen
> `2017/10/06 22:24:07 new cron: 0 "0 * * * *"`

The problem here is that docker-compose is passing those quotes to a go-cron if environment variables are declared as yaml sequences. Use a dictionary instead: 
```
    environment:
      USERNAME: 'root'
      PASSWORD: 'my-secret-pw'
      DBHOST: 'mysql'
      CRON_SCHEDULE: '0 0 * * *'
```
`2017/11/11 11:59:14 new cron: 0 0 * * * *`

@nepda 
If you already have automysqlbackup container running in a cron mode and want to make a manual backup, do something like this: `docker-compose exec mysqlbackup automysqlbackup`
