### ISSUE TITLE
Got error: 1556: You can't use locks with log tables when using LOCK TABLES

### ISSUE THREAD

**Issue by numo68** [selim13/docker-automysqlbackup#10]
Running this against a MariaDB 10.4.8 I get the error in the subject and the backup of the mysql database does not contain any tables.

```
  mysqlbackup:
    image: selim13/automysqlbackup:2.6-6-debian
    volumes:
      - "mariadb-backup:/backup"
    environment:
      USERNAME: root
      PASSWORD: "..."
      DBHOST: cloudserver_db
      DBEXCLUDE: "performance_schema information_schema"
      CRON_SCHEDULE: "22 22 * * *"
    depends_on:
      - db
```

```
# docker-compose exec mysqlbackup automysqlbackup
mysql: [Warning] Using a password on the command line interface can be insecure.
======================================================================
AutoMySQLBackup VER 2.5
http://sourceforge.net/projects/automysqlbackup/

Backup of Database Server - cloudserver_db
======================================================================
Backup Start Time Wed Oct 2 21:08:36 UTC 2019
======================================================================
Daily Backup of Database ( mysql )
Rotating last weeks Backup...

mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got error: 1556: You can't use locks with log tables when using LOCK TABLES

Backup Information for /backup/daily/mysql/mysql_2019-10-02_21h08m.Wednesday.sql
         compressed        uncompressed  ratio uncompressed_name
                535                1088  56.0% /backup/daily/mysql/mysql_2019-10-02_21h08m.Wednesday.sql
```

The dump contains just a bunch of comments and then

```
--
-- Current Database: `mysql`
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `mysql` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `mysql`;
```

Other databases are dumped just fine. Changes between 2.6-6-debian and latest don't seem to affect anything relevant.

Thanks
