### ISSUE TITLE
Add Support for Ports

### ISSUE THREAD

**Issue by TPGeek** [selim13/docker-automysqlbackup#2]
Hello,

 is it possible for you to add support for custom / bespoke ports please as the SQL service we use, doesn't run on the default port.

Tom

**Comment by selim13** [comment]
I've added DBPORT option. 
New build should already be on the docker hub.
Test it and tell if it works for you.

**Comment by TPGeek** [comment]
On my docker host, It starts up then just stops right away.

**Comment by selim13** [comment]
I've just tested it out, and everything worked perfectly. Need more info.

Here is an example docker-compose file I've used for testing.
```
version: "2"

volumes:
  mysql-data: {}
  mysql-backups-data: {}

services:
  mysql:
    image: mysql:latest
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    command:
      [
      --port=6666
      ]

  mysqlbackup:
    image: selim13/automysqlbackup
    volumes:
      - "mysql-backups-data:/var/lib/mysql"
    environment:
      USERNAME: root
      PASSWORD: "my-secret-pw"
      DBHOST: mysql
      DBPORT: 6666
      CRON_SCHEDULE: "* * * * *"
    depends_on:
      - mysql
```

Logs:
```
...
Backup Information for /backup/daily/performance_schema/performance_schema_2017-12-15_10h34m.Friday.sql
...
```
